INSERT INTO jenis_pelanggarans (kategori_id, jenis_pelanggaran, poin, sub_kategori) VALUES ('1', 'Terlambat (bangun pagi, mengikuti ibadah dan keluar masuk asrama)', '1', 'Ringan');
INSERT INTO jenis_pelanggarans (kategori_id, jenis_pelanggaran, poin, sub_kategori) VALUES ('1', 'Terlambat pulang ke asrama dalam rentan waktu yang lama.', '2', 'Ringan');
INSERT INTO jenis_pelanggarans (kategori_id, jenis_pelanggaran, poin, sub_kategori) VALUES ('1', 'Terlambat melaksanakan tugas piket kebersihan.', '2', 'Ringan');
INSERT INTO jenis_pelanggarans (kategori_id, jenis_pelanggaran, poin, sub_kategori) VALUES ('1', 'Tidak melaksanakan tugas piket kebersihan.', '3', 'Ringan');
INSERT INTO jenis_pelanggarans (kategori_id, jenis_pelanggaran, poin, sub_kategori) VALUES ('1', 'Tidak mengikuti kegiatan/Apel senam/ibadah/evaluasi mahasiswa tanpa seizin Pembina Asrama', '2', 'Ringan');
INSERT INTO jenis_pelanggarans (kategori_id, jenis_pelanggaran, poin, sub_kategori) VALUES ('1', 'Meninggalkan kamar dalam keadaan tidak bersih/rapi.', '2', 'Ringan');
INSERT INTO jenis_pelanggarans (kategori_id, jenis_pelanggaran, poin, sub_kategori) VALUES ('1', 'Meninggalkan lemari dan tempat tidur dalam keadaan tidak bersih, rapi dan layak', '2', 'Ringan');
INSERT INTO jenis_pelanggarans (kategori_id, jenis_pelanggaran, poin, sub_kategori) VALUES ('1', 'Menggunakan seprei atau sarung bantal tidak sesuai warna', '1', 'Ringan');
INSERT INTO jenis_pelanggarans (kategori_id, jenis_pelanggaran, poin, sub_kategori) VALUES ('1', 'Tidak menggunakan seprei/sarung bantal atau tidak menggantinya setelah dipakai dua minggu.', '2', 'Ringan');
INSERT INTO jenis_pelanggarans (kategori_id, jenis_pelanggaran, poin, sub_kategori) VALUES ('1', 'Melalaikan kerapian serta kebersihan lingkungan asrama selasar, area kamar mandi, area penyetrikaan, area pantri dan area lainnya di asrama; seperti: meletakkan barang dengan tidak rapi di tempat tersebut, meletakkan sampah dengan sembarangan, dsb.', '2', 'Ringan');
INSERT INTO jenis_pelanggarans (kategori_id, jenis_pelanggaran, poin, sub_kategori) VALUES ('1', 'Meninggalkan lampu kamar tidur atau lampu asrama dalam keadaan menyala', '2', 'Ringan');
INSERT INTO jenis_pelanggarans (kategori_id, jenis_pelanggaran, poin, sub_kategori) VALUES ('1', 'Meninggalkan keran air dalam keadaan menyala.', '2', 'Ringan');
INSERT INTO jenis_pelanggarans (kategori_id, jenis_pelanggaran, poin, sub_kategori) VALUES ('1', 'Meninggalkan perlengkapan pribadi di sembarangan tempat: handuk, pakaian, peralatan mandi, ember, dan lainnya.', '1', 'Ringan');
INSERT INTO jenis_pelanggarans (kategori_id, jenis_pelanggaran, poin, sub_kategori) VALUES ('1', 'menggunakan fasilitas di asrama tanpa seizin Pembina Asrama ', '2', 'Ringan');
INSERT INTO jenis_pelanggarans (kategori_id, jenis_pelanggaran, poin, sub_kategori) VALUES ('1', 'Mencuci/mandi/menyetrika di luar waktu dan tempat yang telah ditentukan.', '2', 'Ringan');
INSERT INTO jenis_pelanggarans (kategori_id, jenis_pelanggaran, poin, sub_kategori) VALUES ('1', 'Membiarkan/tidak melaporkan kerusakan fasilitas asrama.', '1', 'Ringan');
INSERT INTO jenis_pelanggarans (kategori_id, jenis_pelanggaran, poin, sub_kategori) VALUES ('1', 'Menyimpan gantungan pakaian (hanger) di lemari melebihi ketentuan', '1', 'Ringan');
INSERT INTO jenis_pelanggarans (kategori_id, jenis_pelanggaran, poin, sub_kategori) VALUES ('1', 'Membawa pakaian atau perlengkapan yang tidak sesuai dengan kriteria perlengkapan mahasiswa dan/atau  melebihi batas ketentuan perlengkapan mahasiswa.', '2', 'Ringan');
INSERT INTO jenis_pelanggarans (kategori_id, jenis_pelanggaran, poin, sub_kategori) VALUES ('1', 'Membawa dan memakan nasi di kamar asrama selain karena sakit', '2', 'Ringan');
INSERT INTO jenis_pelanggarans (kategori_id, jenis_pelanggaran, poin, sub_kategori) VALUES ('1', 'Keluar lingkungan asrama dengan menggunakan celana pendek/ baju tidur/sandal jepit.', '2', 'Ringan');
INSERT INTO jenis_pelanggarans (kategori_id, jenis_pelanggaran, poin, sub_kategori) VALUES ('1', 'Tidak melaporkan kehilangan barang pribadi yang dialami.', '1', 'Ringan');
INSERT INTO jenis_pelanggarans (kategori_id, jenis_pelanggaran, poin, sub_kategori) VALUES ('1', 'Tidak melaporkan keadaan diri sedang sakit kepada Pembina Asrama', '1', 'Ringan');
INSERT INTO jenis_pelanggarans (kategori_id, jenis_pelanggaran, poin, sub_kategori) VALUES ('1', 'Tidak meminta tandatangan persetujuan Surat surat Izin Bermalam di Luar /tidak mengembalikan atau tidak membawa surat kembali saat kembali kepada Pembina Asrama.', '2', 'Ringan');
INSERT INTO jenis_pelanggarans (kategori_id, jenis_pelanggaran, poin, sub_kategori) VALUES ('1', 'Membawa barang-barang/perangkat elektronik yang tidak diperkenankan, seperti:  catok rambut, hair dryer, alat pemasak dll', '10', 'Ringan');
INSERT INTO jenis_pelanggarans (kategori_id, jenis_pelanggaran, poin, sub_kategori) VALUES ('1', 'Mencoret, menempel dan memaku benda di dinding asrama.', '15', 'Sedang');
INSERT INTO jenis_pelanggarans (kategori_id, jenis_pelanggaran, poin, sub_kategori) VALUES ('1', 'Memalsukan dokumen: seperti tandatangan Pembina Asrama', '25', 'Sedang');
INSERT INTO jenis_pelanggarans (kategori_id, jenis_pelanggaran, poin, sub_kategori) VALUES ('2', 'Tidak tertib atau ribut di barisan.', '1', 'Ringan');
INSERT INTO jenis_pelanggarans (kategori_id, jenis_pelanggaran, poin, sub_kategori) VALUES ('2', 'Terlambat datang ke kantin setelah jam makan dimulai.', '2', 'Ringan');
INSERT INTO jenis_pelanggarans (kategori_id, jenis_pelanggaran, poin, sub_kategori) VALUES ('2', 'Tidak mandi pada saat makan ke kantin (tanpa alasan kondisi yang dapat diterima)', '1', 'Ringan');
INSERT INTO jenis_pelanggarans (kategori_id, jenis_pelanggaran, poin, sub_kategori) VALUES ('2', 'Mengambil makan diluar porsi seorang ', '1', 'Ringan');
INSERT INTO jenis_pelanggarans (kategori_id, jenis_pelanggaran, poin, sub_kategori) VALUES ('2', 'Menitip nasi atau membawakan nasi orang lain ', '3', 'Ringan');
INSERT INTO jenis_pelanggarans (kategori_id, jenis_pelanggaran, poin, sub_kategori) VALUES ('2', 'Meninggalkan meja/kursi dengan tidak rapi dan tidak bersih setelah digunakan', '2', 'Ringan');
INSERT INTO jenis_pelanggarans (kategori_id, jenis_pelanggaran, poin, sub_kategori) VALUES ('3', 'Terlambat masuk ke lingkungan kampus/asrama ', '1', 'Ringan');
INSERT INTO jenis_pelanggarans (kategori_id, jenis_pelanggaran, poin, sub_kategori) VALUES ('3', 'Tidak melakukan barcode pada saat keluar masuk kampus', '3', 'Ringan');
INSERT INTO jenis_pelanggarans (kategori_id, jenis_pelanggaran, poin, sub_kategori) VALUES ('3', 'Keluar lingkungan kampus di jam akademik tanpa prosedur Izin Keluar di Jam Akademik dan/atau tanpa seizin Pembina asrama', '20', 'Sedang');
INSERT INTO jenis_pelanggarans (kategori_id, jenis_pelanggaran, poin, sub_kategori) VALUES ('4', 'Berpakaian tidak sesuai dengan ketentuan pedoman berbusana di Asrama Polbangtan Malang  pada setiap kegiatan kampus.', '2', 'Ringan');
INSERT INTO jenis_pelanggarans (kategori_id, jenis_pelanggaran, poin, sub_kategori) VALUES ('4', 'Berambut gondrong dan bermodel rambut di luar ketentuan,', '3', 'Ringan');
INSERT INTO jenis_pelanggarans (kategori_id, jenis_pelanggaran, poin, sub_kategori) VALUES ('4', 'Tidak bersepatu di lingkungan asrama', '4', 'Ringan');
INSERT INTO jenis_pelanggarans (kategori_id, jenis_pelanggaran, poin, sub_kategori) VALUES ('4', 'Menggunakan flast shoes untuk putri', '3', 'Ringan');
INSERT INTO jenis_pelanggarans (kategori_id, jenis_pelanggaran, poin, sub_kategori) VALUES ('5', 'Membuang ludah dan atau dahak di sembarangan tempat', '3', 'Ringan');
INSERT INTO jenis_pelanggarans (kategori_id, jenis_pelanggaran, poin, sub_kategori) VALUES ('5', 'Membuang sampah bukan pada tempatnya di lingkungan kampus Asrama Polbangtan Malang', '10', 'Ringan');
INSERT INTO jenis_pelanggarans (kategori_id, jenis_pelanggaran, poin, sub_kategori) VALUES ('5', 'Mencoret dan mengotori dinding bangunan.', '15', 'Sedang');
INSERT INTO jenis_pelanggarans (kategori_id, jenis_pelanggaran, poin, sub_kategori) VALUES ('5', 'Merusak fasilitas di Asrama Polbangtan Malangdengan sengaja dan tidak bertanggungjawab, baik di asrama, kantin maupun lingkungan kampus.', '20', 'Sedang');
INSERT INTO jenis_pelanggarans (kategori_id, jenis_pelanggaran, poin, sub_kategori) VALUES ('6', 'Merokok di asrama', '10', 'Ringan');
INSERT INTO jenis_pelanggarans (kategori_id, jenis_pelanggaran, poin, sub_kategori) VALUES ('6', 'Melakukan/mengajak/ memfasilitasi kegiatan perjudian/indikasi perjudian termasuk menyimpan dan membawa kartu remi, domino, uno dan sejenisnya yang dapat dipergunakan untuk kegiatan perjudian.', '50', 'Berat');
INSERT INTO jenis_pelanggarans (kategori_id, jenis_pelanggaran, poin, sub_kategori) VALUES ('6', 'Membawa/meminum/mengajak meminum keras', '50', 'Berat');
INSERT INTO jenis_pelanggarans (kategori_id, jenis_pelanggaran, poin, sub_kategori) VALUES ('6', 'Membawa, mengedarkan, menggunakan dan memfasilitasi penggunaan obat-obat terlarang.', '100', 'Berat');
INSERT INTO jenis_pelanggarans (kategori_id, jenis_pelanggaran, poin, sub_kategori) VALUES ('7', 'Tidak melakukan tugas kebersihan lingkungan kampus ', '3', 'Ringan');
INSERT INTO jenis_pelanggarans (kategori_id, jenis_pelanggaran, poin, sub_kategori) VALUES ('7', 'Meletakkan barang-barang pribadi (seperti tas, laptop, gadget) tidak pada tempatnya/dengan sembarangan di lingkungan kampus.', '3', 'Ringan');
INSERT INTO jenis_pelanggarans (kategori_id, jenis_pelanggaran, poin, sub_kategori) VALUES ('7', 'Menggunakan fasilitas lapangan olahraga tidak sesuai kententuan Penggunaan Lapangan yang telah ditentukan ', '2', 'Ringan');
INSERT INTO jenis_pelanggarans (kategori_id, jenis_pelanggaran, poin, sub_kategori) VALUES ('7', 'Meletakkan motor tidak di tempat yang telah ditentukan bagi yang membawa kendaraan', '2', 'Ringan');
INSERT INTO jenis_pelanggarans (kategori_id, jenis_pelanggaran, poin, sub_kategori) VALUES ('7', 'Membawa motor tanpa seizin Tim asrama.', '10', 'Ringan');
INSERT INTO jenis_pelanggarans (kategori_id, jenis_pelanggaran, poin, sub_kategori) VALUES ('7', 'Bersikap tidak sopan/hormat pada Pimpinan, Dosen, Staf dan karyawan', '20', 'Sedang');
INSERT INTO jenis_pelanggarans (kategori_id, jenis_pelanggaran, poin, sub_kategori) VALUES ('7', 'Menghilangkan atau mengubah bukti pelanggaran, absensi, dsb yang bertujuan untuk memanipulasi data.', '25', 'Sedang');
INSERT INTO jenis_pelanggarans (kategori_id, jenis_pelanggaran, poin, sub_kategori) VALUES ('7', 'Memberikan keterangan atau informasi yang tidak benar yang dapat mengakibatkan kekacauan kepada keluarga/orangtua memberikan informasi yang tidak benar tentang kampus Asrama Polbangtan Malang', '25', 'Sedang');
INSERT INTO jenis_pelanggarans (kategori_id, jenis_pelanggaran, poin, sub_kategori) VALUES ('7', 'Melakukan provokasi.', '50', 'Berat');
INSERT INTO jenis_pelanggarans (kategori_id, jenis_pelanggaran, poin, sub_kategori) VALUES ('7', 'Menyimpan/memiliki/membagi/menonton materi pornografi atau mengarah kepada pornografi.', '50', 'Berat');
INSERT INTO jenis_pelanggarans (kategori_id, jenis_pelanggaran, poin, sub_kategori) VALUES ('7', 'Melakukan perbuatan pencemaran nama baik kampus dan', '75', 'Berat');
INSERT INTO jenis_pelanggarans (kategori_id, jenis_pelanggaran, poin, sub_kategori) VALUES ('7', 'Melakukan tindakan pelecehan seksual ', '75', 'Berat');